name: agro
description: "Agro App Profesional"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^10.1.2
  # Mantenemos Riverpod en 2.x para no romper tu cÃ³digo actual
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0 
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  build_runner: ^2.4.8
  # Volvemos a versiones estables
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/